### ISSUE TITLE
Consider changing hashlist function to bitwise operator 

### ISSUE THREAD

**Issue by G5Becks** [BendixMa/Dart-Data-Class-Generator#1]
Hi, first of all - Thanks for the cool plugin!

I recently switched to using vscode from using IntelliJ. In IntelliJ / Android Studio, there is a similar plugin to this one that can generate data classes for you, but instead of using the hashlist function from dart:ui , it just combines all of the hashcodes from each property using bitwise and if I am not mistaken.

This has the benefit of not assuming that the user of the plugin is creating a flutter application - which although might not seem common, happens quite often. It seems like it would be quite a simple change that would help quite a bit.

Thanks.

**Comment by BendixMa** [comment]
Hey, thanks for the feedback!

I used the hashList function because it uses the Jenkins SMI hash function, however I have to agree that the bitwise operator is probably more than enough most of the time and as you said doesn't assume that the user is creating a flutter application.

I released a new version (0.2.0) and changed the default hashCode implementation to use the bitwise operator as you suggested. I added a new user setting `dart_data_class_generator.hashCode.use_jenkins` so you can switch between hashList and bitwise when needed.

I hope that helps!

**Comment by G5Becks** [comment]
Thanks a lot for adding this feature so quickly. Have a great day!
