### ISSUE TITLE
Option to configure type of Equatable integration

### ISSUE THREAD

**Issue by ened** [BendixMa/Dart-Data-Class-Generator#9]
Great extension!
It would be nice to configure the type of Equatable inclusion, e.g. whether it's using the Mixin or inheritance method. Currently, the generator defaults to mixin.

Eg:
```
class SomeVS with EquatableMixin { }
```

vs.
```
class SomeVS extends Equatable { }
```

**Comment by BendixMa** [comment]
Yeah, that would probably make sense.

I think the author of equatable changed the implementation of `Equatable` to always use the `props` getter instead of passing them to the `super constructor`, since I've written this. This was the reason I used the `mixin` in the first place. 

I guess the generator should check whether the class has a superclass and if it does, the generator should use the mixin. Otherwise, the normal inheritance way would be used. This would probably be the most convenient way instead of adding an additional setting.

**Comment by BendixMa** [comment]
I released version `0.3.10` that should fix this issue as I have outlined in my previous comment.

**Comment by ened** [comment]
Wow that is very kind of you. I’ll check it out later today.

**Comment by ened** [comment]
Works really well. Thank you!
